name: Test PR

on:
  push:
    branches: [ main,  ]
  pull_request:
    branches: [ main, release/* ]

jobs:
  changedfiles:
    runs-on: ubuntu-latest
    
    # Map a step output to a job output
    outputs:
      all: ${{ steps.changes.outputs.all}}
      ts: ${{ steps.get_file_changes.outputs.files_added }}  grep .ts$ | xargs

    steps:
        # Make sure we have some code to diff.
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
          
      - name: Install dependency
        run: npm ci     
        
      - name: Get file changes
        id: get_file_changes
        uses: trilom/file-changes-action@v1.2.3
        with:
          output: ' '
          
      - name: Echo file changes
        id: hello
        run: |
              echo Added files: ${{ steps.get_file_changes.outputs.files_added }}
              echo Changed files: ${{ steps.get_file_changes.outputs.files_modified }}
              echo Removed files: ${{ steps.get_file_changes.outputs.files_removed }}
      
      - name: Asdf 
        run: |
          echo "TS only ${{ outputs.ts }} "
          
      - name: TSLint Checking
        if: ${{ always() && (steps.get_file_changes.outputs.files_added || steps.get_file_changes.outputs.files_modified) }}
        # tslint [options] [file ...]
        run: $(git rev-parse --show-toplevel)/node_modules/.bin/tslint -p $(git rev-parse --show-toplevel) ${{ steps.get_file_changes.outputs.files_added }} ${{ steps.get_file_changes.outputs.files_modified }}
  







        
        
